// Short-lived signed challenge cookies for the WebAuthn register /
// authenticate ceremonies.
//
// The cookie is separate from the session cookie so:
//   * register/finish and authenticate/finish can be POSTed without an
//     existing session (register happens BEFORE the first session exists);
//   * the challenge cookie's Max-Age is 5 minutes vs 24h for sessions;
//   * the Path is scoped to /api/auth/passkey so it isn't attached to
//     unrelated requests.
//
// Token shape matches session.ts: <payload-b64url>.<hmac-hex>. Same
// SESSION_SIGNING_KEY signs both.

const COOKIE_NAME = 'fluxtube_challenge';
const MAX_AGE_SECONDS = 60 * 5; // 5m — enough for the user to touch the key

export type ChallengePurpose = 'register' | 'authenticate';

export interface ChallengeData {
  purpose: ChallengePurpose;
  value: string; // base64url random bytes generated by @simplewebauthn/server
  issuedAt: number;
}

export async function signChallenge(data: ChallengeData, hmacKeyB64: string): Promise<string> {
  const key = await importHmacKey(hmacKeyB64);
  const payloadJson = JSON.stringify(data);
  const payloadB64Url = base64UrlEncode(new TextEncoder().encode(payloadJson));
  const mac = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(payloadB64Url));
  return `${payloadB64Url}.${bytesToHex(new Uint8Array(mac))}`;
}

/** Verifies + parses. Returns the challenge string iff (signature + TTL + purpose) all check. */
export async function verifyChallenge(
  token: string | undefined,
  hmacKeyB64: string,
  expectedPurpose: ChallengePurpose,
  now: number = Math.floor(Date.now() / 1000),
): Promise<string | null> {
  if (!token) return null;
  const dot = token.indexOf('.');
  if (dot < 1 || dot === token.length - 1) return null;
  const payloadB64Url = token.slice(0, dot);
  const macHex = token.slice(dot + 1);

  const key = await importHmacKey(hmacKeyB64);
  const macBytes = hexToBytes(macHex);
  if (!macBytes) return null;
  const ok = await crypto.subtle.verify(
    'HMAC',
    key,
    macBytes,
    new TextEncoder().encode(payloadB64Url),
  );
  if (!ok) return null;

  let payload: ChallengeData;
  try {
    const raw = base64UrlDecode(payloadB64Url);
    payload = JSON.parse(new TextDecoder().decode(raw)) as ChallengeData;
  } catch {
    return null;
  }
  if (payload.purpose !== expectedPurpose) return null;
  if (typeof payload.value !== 'string' || payload.value.length === 0) return null;
  if (typeof payload.issuedAt !== 'number') return null;
  if (now - payload.issuedAt > MAX_AGE_SECONDS) return null;
  if (payload.issuedAt > now + 60) return null;
  return payload.value;
}

export function challengeCookieHeader(token: string): string {
  return [
    `${COOKIE_NAME}=${token}`,
    'Path=/api/auth/passkey',
    'Secure',
    'HttpOnly',
    'SameSite=Strict',
    `Max-Age=${MAX_AGE_SECONDS}`,
  ].join('; ');
}

export function clearChallengeCookieHeader(): string {
  return [
    `${COOKIE_NAME}=`,
    'Path=/api/auth/passkey',
    'Secure',
    'HttpOnly',
    'SameSite=Strict',
    'Max-Age=0',
  ].join('; ');
}

export function readChallengeCookie(request: Request): string | undefined {
  const cookieHeader = request.headers.get('Cookie');
  if (!cookieHeader) return undefined;
  for (const pair of cookieHeader.split(';')) {
    const trimmed = pair.trim();
    if (trimmed.startsWith(`${COOKIE_NAME}=`)) {
      return trimmed.slice(COOKIE_NAME.length + 1);
    }
  }
  return undefined;
}

async function importHmacKey(b64: string): Promise<CryptoKey> {
  const raw = base64Decode(b64);
  return crypto.subtle.importKey(
    'raw',
    raw,
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign', 'verify'],
  );
}

// base64 helpers duplicated from session.ts. Kept per-file for phase-boundary
// clarity; can lift into a shared _b64.ts if a third caller appears.
function base64Encode(bytes: Uint8Array): string {
  let s = '';
  for (const b of bytes) s += String.fromCharCode(b);
  return btoa(s);
}
function base64Decode(s: string): Uint8Array {
  const bin = atob(s);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
function base64UrlEncode(bytes: Uint8Array): string {
  return base64Encode(bytes).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}
function base64UrlDecode(s: string): Uint8Array {
  const padded = s.replace(/-/g, '+').replace(/_/g, '/') + '='.repeat((4 - (s.length % 4)) % 4);
  return base64Decode(padded);
}
function bytesToHex(bytes: Uint8Array): string {
  let s = '';
  for (const b of bytes) s += b.toString(16).padStart(2, '0');
  return s;
}
function hexToBytes(hex: string): Uint8Array | null {
  if (hex.length % 2 !== 0) return null;
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) {
    const byte = parseInt(hex.substr(i * 2, 2), 16);
    if (Number.isNaN(byte)) return null;
    out[i] = byte;
  }
  return out;
}
